### ISSUE TITLE
base_vrf.py does not implement handlers for CPS get

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-nas-linux#20]
[base_vrf.py](https://github.com/open-switch/opx-nas-linux/blob/master/scripts/bin/base_vrf.py) provides handlers for CPS "transaction" requests.
However it does not provided handlers for CPS "get" requests.

At the moment, a user _can_ use Linux network commands to query the running configuration.
However, it is awkward and requires the user to understand the mapping between the CPS YANG model and Linux networking config. If CPS is the intended method for configuring VRFs, then this mapping should be hidden behind the CPS API.

It would therefore be better for developers and end-users if the above script also provided handlers for CPS "get" requests.

**Comment by GarrickHe** [comment]
Hello @james-jra ,

I'll take a look at this. Will keep you posted.

Thanks,
Garrick

**Comment by GarrickHe** [comment]
Hello @james-jra ,
Still working on this. Will continue to keep you posted.

Thanks,
garrick

**Comment by jeff-yin** [comment]
The fix for this will be released with OPX 3.0.0 due to dependencies on code in that release.

**Comment by jeff-yin** [comment]
This is being addressed by https://github.com/open-switch/opx-nas-common/pull/26

**Comment by GarrickHe** [comment]
This PR is also related to this issue:

https://github.com/open-switch/opx-nas-interface/pull/45
